version: '3.7'
services:
  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    restart: always
    volumes:
      - ./build/mysql/conf:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  adminer:
    image: adminer
    restart: on-failure
    networks:
      - frontend
      - backend
    depends_on:
      - php-app
      - mysql
    ports:
      - "${ADMINER_PORT}:8080"
  apache:
    build: './build/apache/'
    restart: on-failure
    volumes:
      - './app/:/var/www/html/'
    ports:
      - "${APACHE_HTTP}:80"
      - "${APACHE_HTTPS}:443"
    depends_on:
      - php-app
      - mysql
    networks:
      - frontend
      - backend
  php-app:
    build:
      context: .
      dockerfile: './build/php/Dockerfile'
    networks:
      - backend
    volumes:
      - ./app/:/var/www/html/:cached
      - ./logs/php:/var/log
    restart: always
    user: ${LOCAL_USER}
    depends_on:
      - mysql
networks:
  backend:
  frontend: